### ISSUE TITLE
Syntax: We should be able to pass config to the sub attributes

### ISSUE THREAD

**Issue by eyadof** [deriv-com/perl-Myriad#189]
for instance, we have the receiver configured like this: 
```
async method get_something :Receiver(service => '', ...) ($src) {

}
```

currently, we are unable to pass anything but simple scalars to configure `service` that's limiting our abilities to point the same code to a different service instance (staging/production) through the config.

Two reasons for this limitation: 
1. the parameters o the sub-attributes are parsed through an `eval` statement.
2. the configs are not available at the compile time, they are available at some stage after Myriad is actually running.

**Comment by tom-binary** [comment]
Since configuration needs to be dynamic anyway, it shouldn't be part of the attributes - instead, we'd use the config layer for that.
