### ISSUE TITLE
The worker lost RPC calls when there is a lot of calls made into the method

### ISSUE THREAD

**Issue by ngeojiajun-deriv** [deriv-com/perl-Myriad#296]
## Summary
The RPC make uses of the redis stream to store all the pending calls. In myriad this stream can be manipulated by the following futures:
1. The worker to dispatch the RPC call (in the service)
2. Cleanup worker to remove the old item (in the service)
3. Caller (can be either inside or outside the service)

These future are running in parallel, and usually it is safe to use under normal circumstances. 
However inside the high load situation, the cleanup worker (https://github.com/deriv-com/perl-Myriad/blob/master/lib/Myriad/Transport/Redis.pm#L298-L336) might remove too much item than it supposed to be due to the assumption that stream length would be constant during the stream length computation (which introduces the race window). 

To reproduce this, the calling rate need to be higher than the rate the calls are picked up.

## Possible fixes
- Redis 6.2.0 added a new flag which allow us to trim the stream so it would retains all item after the specified ID
- To reduce the race window by considering the number of the entries added between the stream size calculation

Attached this patch as workaround for now:
```diff
diff --git a/lib/Myriad/Transport/Redis.pm b/lib/Myriad/Transport/Redis.pm
index 97e0b15..bd73f13 100644
--- a/lib/Myriad/Transport/Redis.pm
+++ b/lib/Myriad/Transport/Redis.pm
@@ -329,8 +329,16 @@ async method cleanup (%args) {
         }
         $total = $info->{length} - $total if $direction eq 'xrange';
 
+        # As the cleanup operation is NOT atomic, this will introduce a race window
+        # when the caller makes calls in a high rate, we should compensate the number of entries
+        # added during the calculation
+        my ($info2) = await $self->stream_info($stream);
+        my $entries_added = ($info2->{length} - $info->{length});
+        # Add the entries added during the process
+        # gaurd against race trimming by multiple instances of the service
+        $total += int($entries_added);
 #        my ($before) = await $redis->memory_usage($stream);
-        my ($trim) = await $redis->xtrim($stream, MAXLEN => $total);
+        my ($trim) = await $redis->xtrim($stream, MAXLEN => $total) unless $entries_added < 0;
 #        my ($after) = await $redis->memory_usage($stream);
         $log->tracef('Trimmed %d items from stream: %s', $total, $stream);
     }
```

**Comment by tom-binary** [comment]
Since 7.0 is stable and has been out for a while, would suggest dropping the old logic and replacing it all with `await $redis->xtrim($stream, MINID => $oldest)`. It's more efficient and we were planning to do that anyway once the feature was added.

**Comment by ngeojiajun-deriv** [comment]
will prepare a PR for this
