### ISSUE TITLE
Segmentation fault and suspected memory corruption on perl 5.40 (possibly earlier)

### ISSUE THREAD

**Issue by tom-binary** [deriv-com/perl-Myriad#334]
As part of an attempt to track down an elusive segfault issue on perl 5.40, have tried compiling a debug-enabled version of Perl.

This reports the following test failures:

```
t/role.t .............................                                                    
"state" variable  masks earlier declaration in same statement at .../lib/site_perl/5.40.0/x86_64-linux/Object/Pad/MOP/Class.pm line 202.
perl: src/class.c:853: ObjectPad__prepare_adjust_params: Assertion `params_padix == PADIX_PARAMS' failed.
No subtests run
```

We believe the first message about the "state" variable is due to the rôle handling missing a fix that was applied for a similar message reported when creating a class via `Object::Pad::MOP->create_class`.

The more interesting one is the `params_padix` failure - this indicates something has gone out of sync on the pad, which would likely lead to the memory corruption issues we've been seeing elsewhere.

**Comment by tom-binary** [comment]
After further investigation, this specific failure seems to apply only when the experimental `composed_adjust` mode is used.

```
$ perl -e'
 use Object::Pad qw(:experimental(composed_adjust));
 package R; role R { method example; }
 package C; class C :does(R) {
  field $f;
  method example() { }
 }'
perl: src/class.c:853: ObjectPad__prepare_adjust_params: Assertion `params_padix == PADIX_PARAMS' failed.
```

We are enabling this inadvertently in the exception builder here:

https://github.com/deriv-com/perl-Myriad/blob/f4d5128c50e3d5bbead84af765152689db05e237/lib/Myriad/Exception/Builder.pm#L21

which should just be enabling the `mop` feature. Will fix that and try again for stability.

**Comment by leonerd** [comment]
I suspect it's related to `-DDEBUGGING` (which enables the `assert()` checking in the first place), rather than Perl version.

For me, a non-debugging 5.40 doesn't crash:

```
$ cat rtTODO.pl 
 use Object::Pad qw(:experimental(composed_adjust));
 package R; role R { method example; }
 package C; class C :does(R) {
  field $f;
  method example() { }
 }
printf "OK\n"

$ eachperl exec rtTODO.pl

  --- perl5.26.3 --- 
OK

  --- perl5.38.2 --- 
OK

  --- perl5.40.0 --- 
OK

  --- bleadperl --- 
perl: src/class.c:853: ObjectPad__prepare_adjust_params: Assertion `params_padix == PADIX_PARAMS' failed.

----------
perl5.26.3          : 0
perl5.38.2          : 0
perl5.40.0          : 0
bleadperl           : aborted on SIGABRT
```

Though, commenting out the `:experimental(composed_adjust)` part makes it pass on all perls here.

**Comment by leonerd** [comment]
Tracking the underlying Object::Pad upstream on https://rt.cpan.org/Ticket/Display.html?id=154494

**Comment by leonerd** [comment]
A patch to fix that seems simple enough: https://rt.cpan.org/Transaction/Display.html?id=2775505

**Comment by tom-binary** [comment]
So far no further issues after merging #335 - will test the `Object::Pad` patches separately with `composed_adjust` enabled to see if those fix the rôle handling. Thanks!
